allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - '@prisma/client-runtime-utils@7.10.0'
  - '@prisma/client@7.10.0'
  - '@prisma/config@7.10.0'
  - '@prisma/debug@7.10.0'
  - '@prisma/engines@7.10.0'
  - '@prisma/fetch-engine@7.10.0'
  - '@prisma/get-platform@7.10.0'
  - prisma@7.10.0
